ALTER TABLE usuarios
ADD COLUMN IF NOT EXISTS nombre_completo VARCHAR(150) NULL AFTER nickname,
ADD COLUMN IF NOT EXISTS telefono VARCHAR(40) NULL AFTER nombre_completo,
ADD COLUMN IF NOT EXISTS correo_electronico VARCHAR(150) NULL AFTER telefono;
